---
apiVersion: v1
kind: Namespace
metadata:
  name: smokeping
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smokeping
  namespace: smokeping
  labels:
    k8s-app: smokeping
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      k8s-app: smokeping
  template:
    metadata:
      labels:
        k8s-app: smokeping
    spec:
      containers:
      - name: smokeping
        image: linuxserver/smokeping:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/config"
            name: config
          - mountPath: "/data"
            name: data
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Europe/London"
      volumes:
        - name: config
          hostPath:
            path: /mnt/ssd/smokeping/config
            type: Directory
        - name: data
          hostPath:
            path: /mnt/ssd/smokeping/data
            type: Directory
            
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smokeping-ingress
  namespace: smokeping
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: smokeping 
            port: 
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: smokeping
  namespace: smokeping
  labels:
    k8s-app: smokeping
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    k8s-app: smokeping
  type: NodePort 

